l_english:
 group_infantry_title:0 "Foot Battalions"
 group_mobile_title:0 "Infantry Battalions"
 group_armor_title:0 "Armored Battalions"
 group_combat_support_title:0 "Combat Support Battalions"
 group_mobile_combat_support_title:0 "Combat Support Battalions"
 group_armor_combat_support_title:0 "Armored Combat Support Battalions"
 group_support_title:1 "Support Companies"